version: "3.9"

services:
  devmarket:
    build: .
    container_name: devmarket-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - FAST_REFRESH=true
    networks:
      - devmarket-network
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: 3G
        reservations:
          cpus: "0.5"
          memory: 512M

networks:
  devmarket-network:
    driver: bridge
