services:
  dev:
    build:
      context: .
      target: dev
    container_name: devmarket-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - FAST_REFRESH=true
    networks:
      - devmarket-network
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: 3G
        reservations:
          cpus: "0.5"
          memory: 512M

  prod:
    build:
      context: .
      target: prod
    container_name: devmarket-prod
    ports:
      - "8080:80"
    networks:
      - devmarket-network

networks:
  devmarket-network:
    driver: bridge
